import { cpSync, existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

const DATA_DIR = resolve(import.meta.dirname, 'data')

/**
 * Serve the committed ETL artifacts at /data.
 *
 * They deliberately live at the repo root rather than in public/: /data is the
 * versioned pipeline OUTPUT, reviewed in diffs and regenerated by
 * `python etl/run.py`, and burying it inside the app's asset folder would blur
 * that boundary. Vite allows only one publicDir, so dev serves it via
 * middleware and build copies it into dist/.
 */
function dataArtifacts(): Plugin {
  return {
    name: 'data-artifacts',
    configureServer(server) {
      server.middlewares.use('/data', (req, res, next) => {
        const relative = (req.url ?? '').split('?')[0]?.replace(/^\/+/, '')
        if (!relative || relative.includes('..')) return next()
        const file = resolve(DATA_DIR, relative)
        if (!file.startsWith(DATA_DIR) || !existsSync(file)) return next()
        res.setHeader('Content-Type', 'application/json; charset=utf-8')
        res.end(readFileSync(file))
      })
    },
    closeBundle() {
      if (!existsSync(DATA_DIR)) {
        this.warn(
          'No /data directory found. Run `python etl/run.py` before building, ' +
            'or the app will render empty states for every figure.',
        )
        return
      }
      cpSync(DATA_DIR, resolve(import.meta.dirname, 'dist/data'), {
        recursive: true,
      })
    },
  }
}

/**
 * GitHub Pages serves a project site from /<repo>/, not from the domain root.
 * Everything the app requests — the JS bundle, the CSS, and crucially the
 * /data artifacts — has to be prefixed with that, or the page loads and then
 * 404s on every fetch, giving a blank map with no error a reader can see.
 *
 * Dev keeps a root base so `npm run dev` behaves normally; the value is
 * overridable via BASE_PATH for anyone deploying somewhere else.
 */
const REPO_BASE = process.env.BASE_PATH ?? '/global-population-dashboard/'

/**
 * Copy index.html to 404.html.
 *
 * GitHub Pages has no SPA rewrite rule. A deep link like /country/USA is a
 * client-side route with no matching file, so Pages would serve its own 404.
 * Pages does serve a repo's own 404.html for unmatched paths, so shipping a
 * copy of the app there makes deep links boot the router instead.
 */
function spaFallback(): Plugin {
  return {
    name: 'spa-fallback',
    closeBundle() {
      const dist = resolve(import.meta.dirname, 'dist')
      const index = resolve(dist, 'index.html')
      if (existsSync(index)) {
        cpSync(index, resolve(dist, '404.html'))
      }
    },
  }
}

export default defineConfig(({ command, isPreview }) => ({
  // Build AND preview use the Pages base; `vite preview` serves the built
  // dist, which has the base baked into every asset URL, so previewing at
  // root produced a blank page whose assets all fell into the SPA fallback.
  base: command === 'build' || isPreview ? REPO_BASE : '/',
  plugins: [react(), tailwindcss(), dataArtifacts(), spaFallback()],
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
  server: {
    port: 5173,
  },
}))
