import { cpSync, existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

const DATA_DIR = resolve(import.meta.dirname, 'data')

/**
 * Serve the committed ETL artifacts at /data.
 *
 * They deliberately live at the repo root rather than in public/: /data is the
 * versioned pipeline OUTPUT, reviewed in diffs and regenerated by
 * `python etl/run.py`, and burying it inside the app's asset folder would blur
 * that boundary. Vite allows only one publicDir, so dev serves it via
 * middleware and build copies it into dist/.
 */
function dataArtifacts(): Plugin {
  return {
    name: 'data-artifacts',
    configureServer(server) {
      server.middlewares.use('/data', (req, res, next) => {
        const relative = (req.url ?? '').split('?')[0]?.replace(/^\/+/, '')
        if (!relative || relative.includes('..')) return next()
        const file = resolve(DATA_DIR, relative)
        if (!file.startsWith(DATA_DIR) || !existsSync(file)) return next()
        res.setHeader('Content-Type', 'application/json; charset=utf-8')
        res.end(readFileSync(file))
      })
    },
    closeBundle() {
      if (!existsSync(DATA_DIR)) {
        this.warn(
          'No /data directory found. Run `python etl/run.py` before building, ' +
            'or the app will render empty states for every figure.',
        )
        return
      }
      cpSync(DATA_DIR, resolve(import.meta.dirname, 'dist/data'), {
        recursive: true,
      })
    },
  }
}

export default defineConfig({
  plugins: [react(), tailwindcss(), dataArtifacts()],
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
  server: {
    port: 5173,
  },
})
